# Generated by Django 3.0.8 on 2020-07-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('USED', 'used'), ('NEW', 'new')], default='NEW', max_length=4),
        ),
    ]
