# Generated by Django 3.0.8 on 2020-07-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200730_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaliable',
            new_name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
