# Generated by Django 3.0.8 on 2020-07-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200730_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('USED', 'used'), ('NEW', 'new')], default='NEW', max_length=4),
        ),
    ]
