# Generated by Django 3.0.7 on 2020-08-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200810_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('USED', 'used'), ('NEW', 'new')], default='NEW', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=12, verbose_name=models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
        ),
    ]
