# Generated by Django 3.0.8 on 2020-07-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200730_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='canceled',
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW', 'new'), ('USED', 'used')], default='NEW', max_length=4),
        ),
    ]
