# Generated by Django 3.0.7 on 2020-08-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200810_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('USED', 'used'), ('NEW', 'new')], default='NEW', max_length=4),
        ),
    ]
