# Generated by Django 3.0.7 on 2020-08-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200810_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW', 'new'), ('USED', 'used')], default='NEW', max_length=4),
        ),
    ]
