# Generated by Django 3.0.7 on 2020-08-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200810_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('USED', 'used'), ('NEW', 'new')], default='NEW', max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='for_eighteen',
            field=models.BooleanField(default=False),
        ),
    ]
