# Generated by Django 3.0.8 on 2020-08-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_canceled'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
